apiVersion: v1
kind: Service
metadata:
  name: python-todo-app
  labels:
    app: python-todo-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: python-todo-app